# Generated by Django 5.1.2 on 2024-10-27 18:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('total_bot_users', models.IntegerField(default=0)),
                ('webapp_opens', models.IntegerField(default=0)),
                ('ru_users', models.IntegerField(default=0)),
                ('ua_users', models.IntegerField(default=0)),
                ('en_users', models.IntegerField(default=0)),
                ('total_spots', models.IntegerField(default=10000)),
                ('used_spots', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Statistics',
                'verbose_name_plural': 'Statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='first_seen',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='action_data',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='join_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='last_webapp_open',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='referral_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='dashboard.telegramuser'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='tokens',
            field=models.IntegerField(default=5000),
        ),
    ]
