# Generated by Django 5.1.2 on 2024-10-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_statistics_remove_telegramuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='statistics',
            name='chat_members',
            field=models.IntegerField(default=0, help_text='Кількість користувачів у чаті'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='chat_join_date',
            field=models.DateTimeField(blank=True, help_text='Дата приєднання до чату', null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='in_chat',
            field=models.BooleanField(default=False, help_text='Чи є користувач у Telegram чаті'),
        ),
    ]
