# Generated by Django 5.1.2 on 2024-10-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_telegramuser_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='deleted_bot_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='last_status_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='left_chat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='chat_join_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='in_chat',
            field=models.BooleanField(default=False),
        ),
    ]
