# Generated by Django 5.1.2 on 2024-10-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_telegramuser_deleted_bot_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='chat_members',
            field=models.IntegerField(default=0),
        ),
    ]
